### ISSUE TITLE
Having Trouble Building vpython

### ISSUE THREAD

**Issue by OrbitalMechanic** [mwcraig/conda-vpython-recipes#1]
I'm attempting to build vpython in the anaconda distribution on a MacBook Pro running Mac OS X ver. 10.11.5 (El Capitan) under Python 2.7.x.

I attempted to build vpython using the conda-vpython-recipes. The build failed because it could not find libpython2.7.dylib when it was linkiing libpython2.7.dylib in /Users/user/anaconda/envs/_build/lib/libboost_python.dylib (see the attached file).

My other attempt was to use the command conda install -c mwcraig vpython. The hesitation I have here is that using this command would downgrade numpy and scipy from

numpy:          1.10.4-py27_2                               --> 1.9.3-py27_3  
    scipy:         0.17.0-np110py27_4                     --> 0.16.0-np19py27_1
 numexpr:       2.6.0-np110py27_0      anaconda --> 2.4.4-np19py27_0

I'm not sure how to proceed and/or fix this problem.

Please advise.

Sam Dupree.

[VPython_build_report.txt](https://github.com/mwcraig/conda-vpython-recipes/files/321903/VPython_build_report.txt)

This

**Comment by mwcraig** [comment]
Hi Sam,

Thanks for the report, I'd been meaning to update the builds on my conda channel and hadn't gotten around to it. I've done two things:
- Built and uploaded mac versions of vpython for numpy 1.10 and 1.11, so that `conda install -c mwcraig vpython` will not downgrade your numpy.
- Updated the recipes in this repository so they work with current versions of conda and conda-build, in case you still want to build your own.

You may also want to check out https://github.com/vpython-jupyter

**Comment by OrbitalMechanic** [comment]
Matt,

Thanks for your help. The install now works. I appreciate it. :-)

Sam Dupree.
